perf: matrix multiplication (tile prefetch bank)

diff --git a/src/makefile b/src/makefile
--- a/src/makefile
+++ b/src/makefile
@@ -1,15 +1,19 @@
 # src/Makefile
 
 TARGET = main_test
+OBJS=$(BUILD_DIR)/matrix_mul.o
 SRC_DIR = ../src
 BUILD_DIR = ../build
+LOG_DIR = ../log
 NVCC = nvcc
 SUB_DIRS = $(SRC_DIR)/matmul
 COMPILE_FLAG = -I $(SRC_DIR)/include
 
 SCRIPT_DIR = ../script
 EXE_PATH = $(BUILD_DIR)/$(TARGET)
-PERF_OUT_DIR = $(BUILD_DIR)/perf
+PERF_OUT_DIR = $(LOG_DIR)/perf
+
+PERF_NAME ?=
 
 all: build
 
@@ -17,15 +21,19 @@ run: build
 	./$(BUILD_DIR)/$(TARGET)
 
 perf: build
+	@if [ -z "$(PERF_NAME)" ]; then \
+		echo "Error: PERF_NAME is required. Please provide a value for PERF_NAME."; \
+		exit 1; \
+	fi
 	mkdir -p $(PERF_OUT_DIR)
-	sudo $(SCRIPT_DIR)/ncu_nsys_env.sh $(EXE_PATH) $(PERF_OUT_DIR)
+	@LOG_FILE="run_$(shell date +%Y%m%d_%H%M%S)_$(PERF_NAME).log" && \
+	sudo $(SCRIPT_DIR)/ncu_nsys_env.sh $(EXE_PATH) $(PERF_OUT_DIR) | tee "$(PERF_OUT_DIR)/$$LOG_FILE"
 
 build: $(SUB_DIRS) $(TARGET)
 
-$(TARGET): $(SRC_DIR)/main.cu
+$(TARGET): $(SRC_DIR)/main.cu $(OBJS)
 	@mkdir -p $(BUILD_DIR)
-	@OBJS=$(wildcard $(BUILD_DIR)/*.o) && \
-	nvcc $(COMPILE_FLAG) -o $(BUILD_DIR)/$@ $^ $$OBJS
+	nvcc $(COMPILE_FLAG) -o $(BUILD_DIR)/$@ $^
 
 $(SUB_DIRS):
 	$(MAKE) -C $@
@@ -38,5 +46,6 @@ clean:
 
 clean_all:
 	rm -rf $(BUILD_DIR)
+	rm -rf $(LOG_DIR)
 
-.PHONY: all run build clean $(SUB_DIRS)
+.PHONY: all run build clean clean_all $(SUB_DIRS)
